# Docker Compose file for PharmaTrust
# No version needed for Compose V2

services:
  mongo:
    image: mongo:7
    container_name: pharmatrust-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=pharmatrust
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/pharmatrust --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pharmanet

  redis:
    image: redis:7-alpine
    container_name: pharmatrust-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - pharmanet

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: pharmatrust-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "test", "-m", "test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - pharmanet

  auth:
    build: 
      context: ./services/auth
      dockerfile: Dockerfile
    container_name: pharmatrust-auth
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4001
      - MONGO_URL=mongodb://mongo:27017/pharmatrust
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-demo-secret-key-change-in-production}
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "4001:4001"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - pharmanet

  medicine:
    build:
      context: ./services/medicine
      dockerfile: Dockerfile
    container_name: pharmatrust-medicine
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4002
      - MONGO_URL=mongodb://mongo:27017/pharmatrust
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-demo-secret-key-change-in-production}
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "4002:4002"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - pharmanet

  iot:
    build:
      context: ./services/iot
      dockerfile: Dockerfile
    container_name: pharmatrust-iot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4003
      - MONGO_URL=mongodb://mongo:27017/pharmatrust
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-demo-secret-key-change-in-production}
      - WEBSOCKET_PORT=4003
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
    ports:
      - "4003:4003"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - pharmanet

  blockchain:
    build:
      context: ./services/blockchain
      dockerfile: Dockerfile
    container_name: pharmatrust-blockchain
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4004
      - THIRDWEB_SECRET_KEY=${THIRDWEB_SECRET_KEY:-}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS:-}
      - JWT_SECRET=${JWT_SECRET:-demo-secret-key-change-in-production}
      - BLOCKCHAIN_NETWORK=${BLOCKCHAIN_NETWORK:-polygon-mumbai}
    ports:
      - "4004:4004"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - pharmanet

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: pharmatrust-web
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://localhost:80
      - NEXT_PUBLIC_WS_URL=ws://localhost:4003
    depends_on:
      auth:
        condition: service_healthy
      medicine:
        condition: service_healthy
      iot:
        condition: service_healthy
      blockchain:
        condition: service_healthy
      mobile-gateway:
        condition: service_healthy
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - pharmanet

  nginx:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: pharmatrust-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      web:
        condition: service_healthy
      auth:
        condition: service_healthy
      medicine:
        condition: service_healthy
      iot:
        condition: service_healthy
      blockchain:
        condition: service_healthy
      mobile-gateway:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - pharmanet

  mobile-gateway:
    build:
      context: ./services/mobile-gateway
      dockerfile: Dockerfile
    container_name: pharmatrust-mobile-gateway
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4010
      - REDIS_URL=redis://redis:6379
      - AUTH_BASE=http://auth:4001
      - MEDICINE_BASE=http://medicine:4002
      - IOT_BASE=http://iot:4003
      - BLOCKCHAIN_BASE=http://blockchain:4004
      - JWT_SECRET=${JWT_SECRET:-demo-secret-key-change-in-production}
    depends_on:
      auth:
        condition: service_healthy
      medicine:
        condition: service_healthy
      iot:
        condition: service_healthy
      blockchain:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "4010:4010"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - pharmanet

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local

networks:
  pharmanet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
